name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Node.js Kurulumu
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Bağımlılıkları Yükle
      run: npm ci
      
    - name: Linter Kontrolü
      run: npm run lint
      
    - name: Unit Testleri Çalıştır
      run: npm run test:unit
      
    - name: E2E Testleri Çalıştır
      run: npm run test:e2e
      
  build:
    name: Build ve Deploy
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Node.js Kurulumu
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Bağımlılıkları Yükle
      run: npm ci
      
    - name: Production Build
      run: npm run build
      
    - name: Firebase Deploy
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
        projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'
        channelId: live 